### ISSUE TITLE
Integrity test fails with latest go-crypto

### ISSUE THREAD

**Issue by mdosch** [sylabs/sif#309]
Dear sif developers,

building sif with the latest [go-crypto](https://github.com/ProtonMail/go-crypto/commit/7e9e0395ebec101954178e9a81d936121bf999c5) fails the tests for integrity (see attached log). [integrity_test_fail.txt](https://github.com/sylabs/sif/files/11994771/integrity_test_fail.txt)
Maybe the tests can be made more stable by not relying on hardcoded signatures, as a go-crypto developer [stated there](https://github.com/emersion/go-pgpmail/issues/12#issuecomment-1179684311).

Best regards,
Martin

**Comment by tri-adam** [comment]
Hi @mdosch 👋, thanks for the report!

The suggestion to use a sign/verify round trip rather than using golden files for sign tests makes sense to me. On the other hand, we have found value in detecting when a dependency changes causes a (potentially breaking) change to an output format. When this occurs, understanding the change that was made, and verifying that a signature generated with the new version can still be verified by the old version, and vice versa is important to maintain compatibility.

I think there's probably a good middle ground here where the low level tests continue to act as they currently do, but higher level tests rely on sign/verify round trips. This will continue to ensure we investigate when output formats change, while minimizing the amount of work to update golden files in various tests.
