### ISSUE TITLE
Replace Deprecated UUID Package

### ISSUE THREAD

**Issue by tri-adam** [sylabs/sif#7]
The `github.com/satori/go.uuid` module used by this project does not appear to be actively maintained ([ref](https://github.com/satori/go.uuid/issues/84)).

We should consider switching to the `github.com/gofrs/uuid` package, or some other suitable alternative.

**Comment by tri-adam** [comment]
Did a little research into this. The `github.com/gofrs/uuid` package lacks a `go.mod`, with an explanation offered in https://github.com/gofrs/uuid/issues/85. Personally, that feels a little off-putting to me, and I think we'd be wise to consider alternatives.

`github.com/google/uuid` seems to be the other, obvious alternative.

The `uuid.UUID` type is used in two exported struct fields in the SIF API:

https://github.com/sylabs/sif/blob/c2569550de3bf4558ea099237a630ccb9a3b0af8/pkg/sif/sif.go#L270

https://github.com/sylabs/sif/blob/c2569550de3bf4558ea099237a630ccb9a3b0af8/pkg/sif/sif.go#L319

Strictly speaking, the semantics of Go module versioning require a major version bump to implement this backwards incompatible change (see [here](https://blog.golang.org/publishing-go-modules) for more info.)

**Comment by cameracker** [comment]
Hey! 

I wandered into this issue because someone posted on that issue you linked. I wanted to mention that this repo is using a version of satori/go.uuid that has a CVE filed against it because periodically the UUIDs will be about 50% 0's. This problem is fixed on master but the maintainer failed to tag it. 

It seems like the recommendations in the issue here are pretty great! But I'd suggest expediency.

**Comment by tri-adam** [comment]
Thank you for the heads up @cameracker, much appreciated!

I've gone ahead and opened up https://github.com/sylabs/sif/pull/8 as a short-term solution to this that doesn't require a major version bump.
